#! /bin/sh

SCALA_BIN_VER="@SCALA_BIN_VER@"
SCALANATIVE_VER="@SCALANATIVE_VER@"
SCALANATIVE_BIN_VER="@SCALANATIVE_BIN_VER@"

BASE="$(dirname $0)/.."

CLILIB="$BASE/lib/scala-native-cli-assembly_$SCALA_BIN_VER-$SCALANATIVE_VER.jar"
NATIVELIB=""
libs="nativelib clib posixlib windowslib auxlib javalib scalalib"
for lib in $libs; do
    NATIVELIB="${NATIVELIB} $BASE/lib/${lib}_native${SCALANATIVE_BIN_VER}_$SCALA_BIN_VER-$SCALANATIVE_VER.jar"
done

scala -classpath "$CLILIB" scala.scalanative.cli.ScalaNativeLd "$@" ${NATIVELIB}
