#! /bin/sh

SCALA_BIN_VER="@SCALA_BIN_VER@"
SCALANATIVE_VER="@SCALANATIVE_VER@"
SCALANATIVE_BIN_VER="@SCALANATIVE_BIN_VER@"
SCALALIB_2_13_FOR_3_VER="@SCALALIB_2_13_FOR_3_VER@"
SCALA_VER=$(scala -version 2>&1 | grep -i scala | grep -o '[0-9]\.[0-9]\+\.[0-9]\+')

BASE="$(dirname $0)/.."

CLILIB="$BASE/lib/scala-native-cli-assembly_$SCALA_BIN_VER-$SCALANATIVE_VER.jar"
NATIVELIB=""
libs="nativelib clib posixlib windowslib auxlib javalib"
for lib in $libs; do
    NATIVELIB="${NATIVELIB} $BASE/lib/${lib}_native${SCALANATIVE_BIN_VER}_$SCALA_BIN_VER-$SCALANATIVE_VER.jar"
done

NATIVELIB="${NATIVELIB} $BASE/lib/javalib-intf-$SCALANATIVE_VER.jar"
if [ "$SCALA_BIN_VER" = "3" ]; then
    NATIVELIB="${NATIVELIB} $BASE/lib/scalalib_native${SCALANATIVE_BIN_VER}_2.13-${SCALALIB_2_13_FOR_3_VER}+${SCALANATIVE_VER}.jar"
    NATIVELIB="${NATIVELIB} $BASE/lib/scala3lib_native${SCALANATIVE_BIN_VER}_3-${SCALA_VER}+${SCALANATIVE_VER}.jar"
else
    NATIVELIB="${NATIVELIB} $BASE/lib/scalalib_native${SCALANATIVE_BIN_VER}_${SCALA_BIN_VER}-${SCALA_VER}+${SCALANATIVE_VER}.jar"
fi

echo $NATIVELIB
scala -classpath "$CLILIB" scala.scalanative.cli.ScalaNativeLd "$@" ${NATIVELIB}
